Composition {
	CurrentTime = 0,
	RenderRange = { 0, 0 },
	GlobalRange = { 0, 0 },
	CurrentID = 1,
	HiQ = true,
	PlaybackUpdateMode = 0,
	Version = "Node.JS",
	SavedOutputs = 0,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	AutoRenderRange = false,
	Resumable = true,
	OutputClips = {},
	Tools = {
		MainOutput = Saver {
			NameSet = true,
			Inputs = {
				ProcessWhenBlendIs00 = Input {
					Value = 0,
				},
				Clip = Input {
					Value = Clip {
						Filename = "/render/Hello-Fusion-Thumbnail/.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0,
					},
				},
				OutputFormat = Input {
					Value = FuId { "PNGFormat" },
				},
				CreateDir = Input {
					Value = 1,
				},
			},
			ViewInfo = OperatorInfo {
				Pos = { 829, 249 },
			},
		},
	},
	Frames = {},
	Prefs = {},
}